In [1]:
import numpy as np

In [13]:
z=np.array ([[1,2,3],
             [4,5,6]])

In [14]:
print (z.sum())

21


In [15]:
z.sum()

np.int64(21)

In [16]:
type(z)

numpy.ndarray

In [17]:
print(z.sum(axis=0))

[5 7 9]


In [12]:
print(z.sum(axis=1))

[ 6 15]


In [20]:
f=np.array([
           [10,20,30],
           [40,50,60],
           [70,80,90]
           ])

In [21]:
print (f.sum())

450


In [22]:
print (f.sum(0))

[120 150 180]


In [23]:
print(f.sum(1))

[ 60 150 240]


In [24]:
k=np.array ([1,2,3,4,5,6])

In [25]:
print (k>3)

[False False False  True  True  True]


In [26]:
k>3

array([False, False, False,  True,  True,  True])

In [27]:
print (k[k>3])

[4 5 6]


In [28]:
print (k[k % 2 ==0])

[2 4 6]


In [29]:
print (k[k>4])

[5 6]


In [30]:
print (k[(k>2)&(k<6)])

[3 4 5]


In [31]:
j = np.array([10,15,20,25,30,35])

In [32]:
print (j[j >= 20])
print (j[j % 10 == 0])
print (j[(j>15)&(j<35)])

[20 25 30 35]
[10 20 30]
[20 25 30]


In [1]:
##lets practice random in numpy

In [2]:
import numpy as np

In [4]:
print(np.random.randint(1,10,5))

[6 8 1 4 2]


In [32]:
a=(np.random.randint(1,6,1))
print(a)

[1]


In [33]:
print(np.random.rand(5))

[0.82808736 0.86110737 0.40730615 0.07319586 0.67620471]


In [35]:
print (np.random.randn(5))

[ 0.81078832  0.73450743 -0.73855172 -0.3828431   1.18662874]


In [37]:
grades = np.random.randint(0,21,20)
print(grades)

[14 13  6  6  2  5  6 15  4  4  6 19  9  2  0  4  2 18 12  1]


In [40]:
grades = np.random.randint(0,21,20)
print(grades[grades >=10])

[14 17 19 20 20 14 18 11 17 14 18]


In [41]:
a=np.random.randint(50,101,10)
print(a)

[ 53  50  85  66 100  59  93  84  78  74]


In [43]:
a=np.random.randint(50,101,10)
print(a)
print (a[a>=80])

[65 98 81 87 51 97 79 87 53 79]
[98 81 87 97 87]
