In [1]:
import numpy as np

In [2]:
grades = np.array([10,15,20,18,12])
print(grades)

[10 15 20 18 12]


In [3]:
print(grades.mean())

15.0


In [4]:
print(grades.max())

20


In [5]:
print(grades.min())

10


In [6]:
print(grades.sum())

75


In [7]:
print(grades.std())

3.687817782917155


In [8]:
q = np.array([2,4,6,8,10])
print(q.mean())
print(q.max())
print(q.min())
print(q.sum())

6.0
10
2
30


In [29]:
np.random.seed(42)
a=(np.random.randint(1,21,100))
print(a)
print(a.sum())
print(a.mean())

print(a.max())

print(a.min())

print(a.std())

print(a[a>=10]) 

print(sum(a>=10))

                  

[ 7 20 15 11  8  7 19 11 11  4  8  3  2 12  6  2  1 12 12 17 10 16 15 15
 19 12 20  3  5 19  7  9  7 18  4 14 18  9  2 20 15  7 12  8 15  3 14 17
  4 18  8  4  2  6 10  4 18 12  2 10  4 14 16 15  8 14  8 16 13 18 15 13
  9 15 13  1  7  9  1 12  8 11 19 17  8  3  3  1  5 10  7  9  7  9  8 12
  2  1 16  5]
1001
10.01
20
1
5.507258846286417
[20 15 11 19 11 11 12 12 12 17 10 16 15 15 19 12 20 19 18 14 18 20 15 12
 15 14 17 18 10 18 12 10 14 16 15 14 16 13 18 15 13 15 13 12 11 19 17 10
 12 16]
50


In [30]:
import numpy as np


In [31]:
a = np.array([1,2,3])

In [32]:
b=a

In [33]:
b[0] = 99

In [34]:
print(a,b)

[99  2  3] [99  2  3]


In [35]:
a = np.array([1,2,3])

In [37]:
b = a.copy()

In [38]:
b[0] = 99

In [39]:
print (a,b)

[1 2 3] [99  2  3]
