In [3]:
import numpy as np

#lets do it

 lets do some basic stuff
 

In [4]:
a=np.arange(15)

In [9]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
print(a.reshape(3,5))


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [11]:
a.shape

(15,)

In [14]:
b=a.reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
b.shape


(3, 5)

In [16]:
b.ndim

2

In [17]:
b.size

15

In [18]:
b.dtype

dtype('int64')

In [19]:
my_age=np.arange(30)

In [20]:
my_age

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [21]:
my_age.reshape(2,5,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [22]:
my_age.ndim

1

In [23]:
my_age.size

30

In [34]:
days_of_the_year=np.arange(1,366)
                           

In [35]:
days_of_the_year
                           

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [36]:
d=days_of_the_year

In [29]:
d

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [37]:
d.shape

(365,)

lets make a things look like calendar


In [44]:
days=np.arange(1,366)
days

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [50]:
calendar=days[:360].reshape(12,30)


In [51]:
print(calendar)

[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
   19  20  21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48
   49  50  51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78
   79  80  81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
  109 110 111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138
  139 140 141 142 143 144 145 146 147 148 149 150]
 [151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168
  169 170 171 172 173 174 175 176 177 178 179 180]
 [181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
  199 200 201 202 203 204 205 206 207 208 209 210]
 [211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228
  229 230 231 232 233 234 235 236 237 238 239 240]


In [59]:
calendar_realweeks=days[:364].reshape(52,7)

In [61]:
calendar_realweeks

array([[  1,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28],
       [ 29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42],
       [ 43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56],
       [ 57,  58,  59,  60,  61,  62,  63],
       [ 64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77],
       [ 78,  79,  80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89,  90,  91],
       [ 92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111, 112],
       [113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126],
       [127, 128, 129, 130, 131, 132, 133],
       [134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147],
       [148, 149, 150, 151, 152, 153, 154],
       [155, 156, 157, 158, 159,

In [62]:
calendar_realweeks.ndim


2

In [65]:
days=np.arange(1,365)

In [67]:
calendar=days.reshape(52,7)

In [68]:
print(calendar)

[[  1   2   3   4   5   6   7]
 [  8   9  10  11  12  13  14]
 [ 15  16  17  18  19  20  21]
 [ 22  23  24  25  26  27  28]
 [ 29  30  31  32  33  34  35]
 [ 36  37  38  39  40  41  42]
 [ 43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56]
 [ 57  58  59  60  61  62  63]
 [ 64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77]
 [ 78  79  80  81  82  83  84]
 [ 85  86  87  88  89  90  91]
 [ 92  93  94  95  96  97  98]
 [ 99 100 101 102 103 104 105]
 [106 107 108 109 110 111 112]
 [113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126]
 [127 128 129 130 131 132 133]
 [134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147]
 [148 149 150 151 152 153 154]
 [155 156 157 158 159 160 161]
 [162 163 164 165 166 167 168]
 [169 170 171 172 173 174 175]
 [176 177 178 179 180 181 182]
 [183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196]
 [197 198 199 200 201 202 203]
 [204 205 206 207 208 209 210]
 [211 212 213 214 215 216 217]
 [218 219 220 221 222 223 224]
 [225 22

In [69]:
print(calendar.size)
print(calendar.ndim)
print(calendar.dtype)
print(calendar.shape)

364
2
int64
(52, 7)


#try another things

In [2]:
import numpy as np

In [7]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
np.ones((8,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [19]:
b=np.array([20,30,40,50])
c=np.arange(4)

In [16]:
b

array([20, 30, 40, 50])

In [20]:
c

array([0, 1, 2, 3])

In [23]:
c-b

array([-20, -29, -38, -47])

In [19]:
b-c

array([20, 29, 38, 47])

In [21]:
c*b


array([  0,  30,  80, 150])

In [24]:
b*c

array([  0,  30,  80, 150])

In [25]:
b>1

array([ True,  True,  True,  True])

In [29]:
b>44

array([False, False, False,  True])

In [30]:
c>b

array([False, False, False, False])

In [31]:
np.sin(c)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [32]:
np.cos(b)

array([ 0.40808206,  0.15425145, -0.66693806,  0.96496603])

In [16]:
import numpy as np

In [17]:
q=np.array([30,40,50,60,70])

In [18]:
q

array([30, 40, 50, 60, 70])

In [19]:
print(q)


[30 40 50 60 70]


In [20]:
print (type (q))

<class 'numpy.ndarray'>


In [21]:
q.shape

(5,)

In [22]:
print(q[0])

30


In [23]:
print (q[1])

40


In [24]:
q[3]

np.int64(60)

In [25]:
(q[2])

np.int64(50)

In [30]:
r = np.array([[20,30],[40,50]])

In [31]:
r[0]

array([20, 30])

In [32]:
r[1]

array([40, 50])

In [33]:
print(r[0])

[20 30]


In [34]:
print(r[0][1])

30


In [36]:
print(r[1][0])

40


In [37]:
m = np.array([10,20,30,40,50])

In [38]:
print(m[1:4])

[20 30 40]


In [39]:
m[0:2]

array([10, 20])

In [40]:
print (m[:3])
print (m[2:])
print (m[-1])

[10 20 30]
[30 40 50]
50


In [41]:
v = np.array([1,2,3,4,5,6])


In [42]:
x=v.reshape(2,3)

In [43]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
print(x)

[[1 2 3]
 [4 5 6]]


In [45]:
x=v.reshape(3,2)

In [46]:
print(x)

[[1 2]
 [3 4]
 [5 6]]
